/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;



import static org.junit.Assert.*;

public class LibraryTest {
	/*@Test(expected = RuntimeException.class)
    public final void notMoreThanTwo() throws Exception {
        StringCalculator.add("3,2,3,3");

    }*/
	
	@Test(expected = RuntimeException.class)

    public final void emptyString() throws Exception {

        StringCalculator.add("");

    }
	
	@Test

    public final void returnSum() {
		
        assertEquals(StringCalculator.add("1,2"),3);

    }

	@Test

    public final void unknownAmount() {
		
        assertEquals(StringCalculator.add("1,2,4,3,5"),15);

    }
	
	@Test(expected = RuntimeException.class)
	public final void negativeNumbers() throws Exception {
		StringCalculator.add("-1,2");
	}
	
	@Test
	public final void biggerThan1000Ignored() throws Exception {
		assertEquals(StringCalculator.add("1000,2000,3000,999"),1999);
	}
}
